// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookLibraryEF.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20260326201442_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookLibraryEF.Models.Author", b =>
                {
                    b.Property<int>("AuthorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorID"));

                    b.Property<string>("AuthorInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthorID");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorID = 1,
                            AuthorInfo = "English novelist and essayist, journalist and critic.",
                            AuthorName = "George Orwell"
                        },
                        new
                        {
                            AuthorID = 2,
                            AuthorInfo = "American novelist best known for To Kill a Mockingbird.",
                            AuthorName = "Harper Lee"
                        },
                        new
                        {
                            AuthorID = 3,
                            AuthorInfo = "American essayist and short story writer.",
                            AuthorName = "F. Scott Fitzgerald"
                        },
                        new
                        {
                            AuthorID = 4,
                            AuthorInfo = "American writer known for The Catcher in the Rye.",
                            AuthorName = "J.D. Salinger"
                        },
                        new
                        {
                            AuthorID = 5,
                            AuthorInfo = "English novelist known primarily for her six major novels.",
                            AuthorName = "Jane Austen"
                        },
                        new
                        {
                            AuthorID = 6,
                            AuthorInfo = "The author information for this book is not registered in the system.",
                            AuthorName = "Unknown Author"
                        });
                });

            modelBuilder.Entity("BookLibraryEF.Models.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookID"));

                    b.Property<int>("AuthorID")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookID");

                    b.HasIndex("AuthorID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookID = 1,
                            AuthorID = 1,
                            ImageUrl = "/images/books/1984 Cover.jpg",
                            Price = 3.1000000000000001,
                            ReleaseYear = 1949,
                            Title = "1984"
                        },
                        new
                        {
                            BookID = 2,
                            AuthorID = 2,
                            ImageUrl = "/images/books/To Kill A Mockingbird Cover.jpg",
                            Price = 4.2000000000000002,
                            ReleaseYear = 1960,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            BookID = 3,
                            AuthorID = 3,
                            ImageUrl = "/images/books/The Great Gatsby Cover.jpg",
                            Price = 3.6000000000000001,
                            ReleaseYear = 1925,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            BookID = 4,
                            AuthorID = 4,
                            ImageUrl = "/images/books/The Catcher in the Rye Cover.jpg",
                            Price = 2.7999999999999998,
                            ReleaseYear = 1951,
                            Title = "The Catcher in the Rye"
                        },
                        new
                        {
                            BookID = 5,
                            AuthorID = 5,
                            ImageUrl = "/images/books/Pride and Prejudice Cover.jpg",
                            Price = 4.5,
                            ReleaseYear = 1813,
                            Title = "Pride and Prejudice"
                        });
                });

            modelBuilder.Entity("BookLibraryEF.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BookUser", b =>
                {
                    b.Property<int>("BooksBookID")
                        .HasColumnType("int");

                    b.Property<int>("UsersUserID")
                        .HasColumnType("int");

                    b.HasKey("BooksBookID", "UsersUserID");

                    b.HasIndex("UsersUserID");

                    b.ToTable("BookUser");
                });

            modelBuilder.Entity("BookLibraryEF.Models.Book", b =>
                {
                    b.HasOne("BookLibraryEF.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("BookUser", b =>
                {
                    b.HasOne("BookLibraryEF.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksBookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookLibraryEF.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookLibraryEF.Models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
